"""'cpricopobre'

Revision ID: 1a773c6e394b
Revises: adc1fdde1a1c
Create Date: 2021-09-25 16:38:30.068487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a773c6e394b'
down_revision = 'adc1fdde1a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cp_pobre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resistencia', sa.Integer(), nullable=True),
    sa.Column('ensaio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ensaio_id'], ['ensaios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cp_rico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resistencia', sa.Integer(), nullable=True),
    sa.Column('ensaio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ensaio_id'], ['ensaios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cp_piloto', sa.Column('ensaio_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'cp_piloto', type_='foreignkey')
    op.create_foreign_key(None, 'cp_piloto', 'ensaios', ['ensaio_id'], ['id'])
    op.drop_column('cp_piloto', 'piloto_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cp_piloto', sa.Column('piloto_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'cp_piloto', type_='foreignkey')
    op.create_foreign_key(None, 'cp_piloto', 'dosagem_piloto', ['piloto_id'], ['id'])
    op.drop_column('cp_piloto', 'ensaio_id')
    op.drop_table('cp_rico')
    op.drop_table('cp_pobre')
    # ### end Alembic commands ###
