"""'addEnsaiosnodb'

Revision ID: 376f3c26aa4e
Revises: 48a03a1b4f72
Create Date: 2021-09-20 23:22:18.648096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376f3c26aa4e'
down_revision = '48a03a1b4f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ensaios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=True),
    sa.Column('piloto', sa.Integer(), nullable=True),
    sa.Column('rico', sa.Integer(), nullable=True),
    sa.Column('pobre', sa.Integer(), nullable=True),
    sa.Column('cp', sa.Integer(), nullable=True),
    sa.Column('pesobrita', sa.Integer(), nullable=True),
    sa.Column('slump', sa.Integer(), nullable=True),
    sa.Column('umidade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ensaios')
    # ### end Alembic commands ###
