"""'addindice'

Revision ID: 3fd88da18c9e
Revises: 376f3c26aa4e
Create Date: 2021-09-25 12:42:50.073253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd88da18c9e'
down_revision = '376f3c26aa4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dosagem_piloto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alfa', sa.Integer(), nullable=True),
    sa.Column('c_unitario', sa.Integer(), nullable=True),
    sa.Column('a_unitario', sa.Integer(), nullable=True),
    sa.Column('b_unitario', sa.Integer(), nullable=True),
    sa.Column('c_massa', sa.Integer(), nullable=True),
    sa.Column('a_massa', sa.Integer(), nullable=True),
    sa.Column('b_massa', sa.Integer(), nullable=True),
    sa.Column('c_acr', sa.Integer(), nullable=True),
    sa.Column('a_acr', sa.Integer(), nullable=True),
    sa.Column('a_massa_umida', sa.Integer(), nullable=True),
    sa.Column('umidade_agregado', sa.Integer(), nullable=True),
    sa.Column('agua', sa.Integer(), nullable=True),
    sa.Column('indice', sa.Integer(), nullable=True),
    sa.Column('ensaio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ensaio_id'], ['ensaios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dosagem_pobre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alfa', sa.Integer(), nullable=True),
    sa.Column('c_unitario', sa.Integer(), nullable=True),
    sa.Column('a_unitario', sa.Integer(), nullable=True),
    sa.Column('b_unitario', sa.Integer(), nullable=True),
    sa.Column('c_massa', sa.Integer(), nullable=True),
    sa.Column('a_massa', sa.Integer(), nullable=True),
    sa.Column('b_massa', sa.Integer(), nullable=True),
    sa.Column('c_acr', sa.Integer(), nullable=True),
    sa.Column('a_acr', sa.Integer(), nullable=True),
    sa.Column('a_massa_umida', sa.Integer(), nullable=True),
    sa.Column('umidade_agregado', sa.Integer(), nullable=True),
    sa.Column('agua', sa.Integer(), nullable=True),
    sa.Column('ensaio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ensaio_id'], ['ensaios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dosagem_rico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alfa', sa.Integer(), nullable=True),
    sa.Column('c_unitario', sa.Integer(), nullable=True),
    sa.Column('a_unitario', sa.Integer(), nullable=True),
    sa.Column('b_unitario', sa.Integer(), nullable=True),
    sa.Column('c_massa', sa.Integer(), nullable=True),
    sa.Column('a_massa', sa.Integer(), nullable=True),
    sa.Column('b_massa', sa.Integer(), nullable=True),
    sa.Column('c_acr', sa.Integer(), nullable=True),
    sa.Column('a_acr', sa.Integer(), nullable=True),
    sa.Column('a_massa_umida', sa.Integer(), nullable=True),
    sa.Column('umidade_agregado', sa.Integer(), nullable=True),
    sa.Column('agua', sa.Integer(), nullable=True),
    sa.Column('ensaio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ensaio_id'], ['ensaios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    op.drop_table('dosagem_rico')
    op.drop_table('dosagem_pobre')
    op.drop_table('dosagem_piloto')
    op.drop_table('person')
    # ### end Alembic commands ###
