"""'addCppiloto'

Revision ID: adc1fdde1a1c
Revises: 3fd88da18c9e
Create Date: 2021-09-25 16:22:18.824218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc1fdde1a1c'
down_revision = '3fd88da18c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cp_piloto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resistencia', sa.Integer(), nullable=True),
    sa.Column('piloto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['piloto_id'], ['dosagem_piloto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cp_piloto')
    # ### end Alembic commands ###
