"""'addaguacimento'

Revision ID: c8e1568f0b66
Revises: 1a773c6e394b
Create Date: 2021-09-27 23:08:05.862371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e1568f0b66'
down_revision = '1a773c6e394b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dosagem_piloto', sa.Column('agua_cimento', sa.Integer(), nullable=True))
    op.add_column('dosagem_pobre', sa.Column('agua_cimento', sa.Integer(), nullable=True))
    op.add_column('dosagem_rico', sa.Column('agua_cimento', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dosagem_rico', 'agua_cimento')
    op.drop_column('dosagem_pobre', 'agua_cimento')
    op.drop_column('dosagem_piloto', 'agua_cimento')
    # ### end Alembic commands ###
