"""'valorK'

Revision ID: d037db96f4af
Revises: c8e1568f0b66
Create Date: 2021-09-29 12:19:22.576757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd037db96f4af'
down_revision = 'c8e1568f0b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resultados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('k1', sa.Integer(), nullable=True),
    sa.Column('k2', sa.Integer(), nullable=True),
    sa.Column('k3', sa.Integer(), nullable=True),
    sa.Column('k4', sa.Integer(), nullable=True),
    sa.Column('k5', sa.Integer(), nullable=True),
    sa.Column('k6', sa.Integer(), nullable=True),
    sa.Column('ensaio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ensaio_id'], ['ensaios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultados')
    # ### end Alembic commands ###
